### ISSUE TITLE
Floflis security report - June 2019

### ISSUE THREAD

**Issue by danimesq** [Floflis/meta#68]
# Report

- [ ] Beaker browser by @pfrazee (closed issue without replying when I'd asked if he knew Beaker's vulnerabilities - https://github.com/beakerbrowser/beaker/issues/1422)
- [ ] QRL wallet by @jplomas (bad response because QRL wallet haves a high risk vulnerability with required review - also snyk.io have found three - https://github.com/theQRL/qrl-wallet/issues/367)
- [ ] Open Bazaar
- [ ] Noty by @fabiospampinato (doesn't think security reports are relevant for his app - https://github.com/fabiospampinato/noty/issues/10)
- [ ] Electron Video Downloader
- [ ] GDevelop
- [ ] Floflis Central

* Report available in https://floflis.github.io/security/reports/06-2019/
* [App scores](https://github.com/Floflis/meta/issues/68#issuecomment-504833724)

**Comment by DaniellMesquita** [comment]
# App scores

- QRL Wallet with security report response by @jplomas:

> Thanks. There are certainly some considerations here for best practices when using Electron but there are not any identified vulnerabilities here. We'd certainly be interested in any identified exploits arising from the way Electron is used within the QRL wallet.

Beaker browser's developer said parsing errors aren't vulnerabilities. Now the QRL Wallet developer says Electronegativity is just pointing Electron's best practices.
They are vulnerabilities, and anything a software can't parse it also can't see hidden vulnerabilities.
Also, Snyk.io have found three vulnerabilities.
`QRL Wallet` **score**: 2 (for having a response and for using a audit app with a badge on its README.md)

- Beaker browser with security report response by @pfrazee:

> I appreciate you running a security audit on the browser, but are any of these results important? I scanned through them and didn't see anything I don't already know about.

After I'd replied and asked ```
If Electronegativity, as a security auditor and not a JS-best-practices program, I think these results are important.
Well, you already knew about?
``` he closed the issue without replying.
`Beaker browser` **score**: 0 (because a browser is the most sensitive Electron app, did a controversial behavior when ignoring a question and Beaker isn't committed for security auditing)

- Noty with security report response by @fabiospampinato:

> I don't think they are relevant for this app.

`Noty` **score**: removed from pre-installed apps (with a short answer, doesn't thinks security is relevant for his app)
